import type { Content } from "./types";

export const en: Content = {
  meta: {
    title: "Sarina Zeitooni — Senior Front-End Developer",
    description:
      "Portfolio of Sarina Zeitooni — senior front-end developer with 5+ years building scalable React, Next.js, and TypeScript applications.",
  },
  profile: {
    name: "Sarina Zeitooni",
    title: "Senior Front-End Developer",
    location: "Tehran, Iran",
    email: "zeitoonisarina@gmail.com",
    github: "https://github.com/sarinazeitooni",
    linkedin: "https://www.linkedin.com/in/sarina-zeitooni",
    headline: "I build fast, reliable, scalable front-end systems.",
    summary:
      "Senior front-end developer with 5+ years of experience building scalable web applications with React, Next.js, and TypeScript. My work centers on frontend architecture, complex business workflows, data-heavy interfaces, and reusable component systems—from API integration and state management through polished, maintainable UI delivered in production.",
  },
  ui: {
    nav: {
      skills: "Skills",
      experience: "Experience",
      projects: "Projects",
      contact: "Contact",
    },
    hero: {
      ctaContact: "Get in touch",
      ctaProjects: "View projects",
      github: "GitHub",
      linkedin: "LinkedIn",
    },
    sections: {
      skills: "Skills",
      experience: "Experience",
      projects: "Projects",
      otherWork: "Other work",
      contact: "Contact",
    },
    project: {
      overview: "Overview",
      role: "My role",
      engineering: "Key engineering work",
      technical: "Technical highlights",
      decisions: "Challenges / engineering decisions",
      impact: "Impact",
      viewSource: "View source",
    },
    contact: {
      blurb:
        "Open to senior front-end roles and consulting. The fastest way to reach me is email.",
    },
    a11y: {
      toggleTheme: "Toggle color theme",
      toggleLocale: "Toggle language",
      themeToLight: "Switch to light theme",
      themeToDark: "Switch to dark theme",
      switchToFa: "Switch to Persian",
      switchToEn: "Switch to English",
    },
  },
  skills: [
    {
      group: "Frontend",
      items: [
        "TypeScript",
        "React 19",
        "Next.js 15 (App Router)",
        "Vite",
        "Tailwind CSS",
        "MUI",
        "Headless UI",
      ],
    },
    {
      group: "Architecture & State",
      items: [
        "Zustand",
        "TanStack Query",
        "Service-layer API design",
        "Route guards / RBAC UI",
        "RTL layouts",
      ],
    },
    {
      group: "Data & APIs",
      items: [
        "Axios (client/server split)",
        "JWT refresh queues",
        "REST integrations",
        "Infinite queries & polling",
      ],
    },
    {
      group: "UI & Forms",
      items: [
        "react-hook-form",
        "Zod",
        "Design-system primitives",
        "Dynamic tables & filters",
        "Jalali date UX",
        "Neshan Maps",
      ],
    },
    {
      group: "Tooling & Monitoring",
      items: [
        "Sentry",
        "PostHog",
        "GTM",
        "Docker",
        "ESLint / Prettier / Husky",
        "pnpm",
      ],
    },
  ],
  experience: [
    {
      role: "Frontend Developer",
      company: "Daroom",
      domain: "Healthcare / Online Pharmacy",
      period: "2025 — Present",
      highlights: [
        "Build and evolve Daroom’s customer web app (Next.js App Router): multi-channel medication intake, basket, status-driven order stepper, factor/payment UI, wallet pay, and pharmaceutical consult chat.",
        "Contribute to the multi-role OMS panel (React/Vite/MUI): live order operations, admin user/finance surfaces, delivery workflows, and shared modal/table patterns used across modules.",
        "Own high-churn product paths on the customer app—Rx/OTC/cosmetic funnels with persisted drafts, basket across item types, and the order money path (stepper, factor breakdown, wallet eligibility).",
        "Ship production HTTP reliability: Axios interceptors with a concurrent 401 refresh queue, cookie auth, and FA dashboard protection via a client auth modal pattern.",
        "Raise shared UI quality—Tailwind design tokens and base components on the storefront; BaseModal standardization and admin financial tab reuse on the OMS side.",
        "Wire production observability (Sentry order telemetry, PostHog/GTM where configured) and ship via Docker (Next standalone / nginx static) with lint/format/build gates.",
      ],
      stack: [
        "React",
        "TypeScript",
        "Next.js",
        "Vite",
        "TanStack Query",
        "Zustand",
        "MUI",
        "Tailwind CSS",
        "Zod",
        "Sentry",
      ],
    },
    {
      role: "Front-End Developer",
      company: "Monta",
      domain: "Smart Education & Assessment",
      period: "2021 — 2025",
      highlights: [
        "Built and maintained production React/Next.js web apps, including an SSR study planner with Redux and integrations to external educational APIs.",
        "Worked on learning and e-commerce surfaces—catalogue/course experiences, cart flows, responsive UI, and performance-minded asset work.",
        "Participated in code review and mentoring within the frontend team.",
      ],
      stack: ["React", "Next.js", "TypeScript", "Redux", "Tailwind CSS"],
    },
    {
      role: "Front-End Developer",
      company: "ParsWeb Solutions",
      domain: "Data Platforms",
      period: "2021",
      highlights: [
        "Built a React data-entry interface with ag-Grid, including drag-and-drop row reordering and bulk editing workflows.",
        "Added client-side Excel and PDF export for operational reporting.",
      ],
      stack: ["React", "ag-Grid", "JavaScript"],
    },
  ],
  projects: [
    {
      name: "Daroom Customer App (rx-panel)",
      tagline: "Prescription-to-delivery pharmacy ordering for patients",
      featured: true,
      note: "Proprietary — source is not public.",
      sections: {
        overview:
          "Persian RTL customer web app (and Bale messenger mini-app surface) for Daroom: electronic and paper prescriptions, OTC/cosmetic requests, catalog (“vitrin”), basket, fulfillment tracking, wallet payment, map-based addresses, and pharmaceutical consultation chat. Next.js App Router SPA/SSR hybrid.",
        role: "Frontend engineer on the customer app—largest commit footprint in a multi-author repo—focused on intake funnels, basket, order lifecycle/payment UI, auth UX, counselling chat, and design-system evolution.",
        engineering: [
          "Built multi-channel medication intake (e-Rx, paper Rx photo, OTC search/dosage, cosmetic) with react-hook-form + Zod, catalog suggest/search, and Zustand-persisted drafts so mid-funnel refresh does not lose work.",
          "Designed the status-driven order stepper: maps backend basket statuses to UI steps, payment substeps, and factor breakdown (items, delivery, services, discounts, wallet).",
          "Implemented wallet payment on the order path—eligibility only in waiting-for-payment, remainder calculation wired into factor/pay without duplicating amounts across components.",
          "Developed multi-type basket (RX / paper / OTC / vitrin) with edit/delete/dispatch and iterative quantity/price loading fixes.",
          "Built pharmaceutical consultation chat with text/file send, optimistic local messages, and 60s polling.",
          "Refactored global client state from React Context to Zustand; split browser vs SSR Axios clients; evolved OTP auth into a global modal with cookie tokens and a concurrent 401 refresh queue.",
          "Integrated address/map UX (province/city from map, search) on top of the shared Neshan stack; shipped FA/EN landings subset via next-intl.",
        ],
        technical: [
          "Next.js 15 App Router",
          "React 19",
          "TypeScript (strict)",
          "Tailwind CSS v4",
          "Zustand + persist",
          "TanStack Query v5",
          "Axios",
          "react-hook-form + Zod",
          "next-intl",
          "Neshan Maps",
          "Sentry / PostHog / GTM",
          "Docker standalone",
        ],
        decisions: [
          "Derive order UI steps from backend status (with optional trace override) instead of a free-form client state machine—keeps payment and fulfillment in sync with ops.",
          "Persist funnel drafts in localStorage and autosubmit after login so auth interrupt does not abandon a partially filled Rx/OTC request.",
          "Use a single refresh-token queue for concurrent 401s; gate Sentry/GTM/PostHog/Bale by an environment matrix (web vs mini-app vs daroom.io).",
          "Invest in shared base UI and token migration inside a shipping RTL product rather than introducing a separate Storybook-led design system.",
        ],
        impact: [
          "Shipped the revenue-critical post-inquiry path: factor clarity, wallet + gateway pay, and live order tracking against a multi-status fulfillment lifecycle.",
          "Unified four acquisition funnels on shared schema/persist/uploader/auth-callback patterns, reducing one-off form implementations.",
          "Hardened client HTTP session handling (refresh queue, session-expiry → auth modal) and chunk-load error recovery after deploys.",
        ],
      },
      stack: [
        "Next.js",
        "React",
        "TypeScript",
        "TanStack Query",
        "Zustand",
        "Zod",
        "Tailwind CSS",
      ],
    },
    {
      name: "Daroom OMS Panel",
      tagline: "Multi-role operations console for pharmacy order management",
      featured: true,
      note: "Proprietary — source is not public.",
      sections: {
        overview:
          "Persian RTL SPA for pharmacy/order operations across Vendor, Admin, and Doctor roles: live and archive order queues, multi-tab order workspaces, admin CRM-style user profiles, wallets/liquidation, delivery, complaints, coupons, doctor visits/patients, vendor reports, and map-based addresses.",
        role: "Frontend engineer on a collaborative OMS codebase—contributing across order domain UI, admin user/finance surfaces, delivery workflows, and shared modal infrastructure within a role-split service-layer architecture.",
        engineering: [
          "Built and iterated dense order-domain UI: regulated/sourcing pricing, commission management, delivery/shipping/tracking flows, and related status actions inside the live operations console.",
          "Designed shared admin finance presentation—tabbed customer/doctor/vendor detail layouts and a reusable UserFinancialTab (including vendor wallet on the admin financial surface).",
          "Implemented BaseModal standardization (actions, form mode, responsive bottom sheet) and refactored existing modals onto it.",
          "Added vendor desktop working-hours UI and a JSON formatter/code-block component for admin payment metadata.",
          "Worked within the panel’s auth and data stack: cookie JWT + deduped refresh, permission-aware routes/menus, React Query service hooks, and Zustand for ops/UI state (polling-driven current-order console).",
        ],
        technical: [
          "React 19",
          "TypeScript (strict)",
          "Vite",
          "MUI 7",
          "TanStack Query",
          "Zustand",
          "Axios",
          "react-hook-form + Zod",
          "Recharts",
          "Neshan Maps",
          "Sentry",
          "Docker + nginx",
        ],
        decisions: [
          "Mirror backend domains with role-split services and guarded lazy routes so Vendor/Admin/Doctor surfaces stay permission-aware without a public marketing shell.",
          "Bridge React Query ↔ Zustand for the current-order console (polling, status counts, notifications) so list ops state stays coherent under mutation invalidation.",
          "Control MUI/maps/query/form/chart weight via Vite manualChunks and lazy-loaded map CSS so the ops SPA stays manageable as modules grow.",
        ],
        impact: [
          "Strengthened the operational deep-dive surface operators live in daily: order workspace tabs, pricing/sourcing/delivery actions, and admin finance/profile tabs.",
          "Reduced modal inconsistency by introducing a shared BaseModal API adopted across order and admin flows.",
          "Kept money-adjacent admin views (wallets, liquidation-related finance UI, payment metadata) readable and reusable across user roles.",
        ],
      },
      stack: [
        "React",
        "TypeScript",
        "Vite",
        "MUI",
        "TanStack Query",
        "Zustand",
        "Zod",
      ],
    },
    {
      name: "Digikala Clone",
      tagline: "E-commerce front-end built end-to-end",
      description:
        "A full e-commerce experience — product listing and detail pages, shopping cart, responsive UI and REST integration with Context API state management.",
      highlights: [
        "Cart and checkout flow with persistent client state.",
        "Responsive layout across breakpoints.",
      ],
      stack: ["TypeScript", "React", "Context API", "REST"],
      repo: "https://github.com/sarinazeitooni/digikala",
    },
    {
      name: "Decamond Login Dashboard",
      tagline: "Authentication flow and dashboard",
      description:
        "A login-to-dashboard flow with validated forms, protected routing and a clean, responsive dashboard shell.",
      highlights: [
        "Form validation and session persistence.",
        "Protected routes with redirect handling.",
      ],
      stack: ["Next.js", "TypeScript"],
      repo: "https://github.com/sarinazeitooni/decamond",
    },
  ],
};
